# Generated by Django 5.2.3 on 2025-06-28 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_remove_video_likes_video_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='count_views',
            field=models.IntegerField(default=0),
        ),
    ]
